# Site settings
title: Miguel Fernández
description: My personal web page
#favicon: /assets/img/avatar.JPG
baseurl: https://mfernam.github.io
url: https://mfernam.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Miguel Fernández
  title: Consultor y desarrollador
  address: Alicante, Spain
  email: losmeus@gmail.com
  link: http://mfernam.github.io
  weibo:
  github: mfernam
  linkedin: mfernam
  twitter: mfernam
#  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  languages:
    - language1:
      name: Spanish
      proficiency: Native
    - language2:
      name: English
      proficiency: Intermediate
    - language3:
      name: French
      proficiency: Limit
    - language4:
      name: Portuguese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C#
      percentage: 100%
    - skill2:
      name: PHP
      percentage: 100%
    - skill3:
      name: Java
      percentage: 70%
    - skill4:
      name: SQL
      percentage: 90%
