# Site settings
title: Miguel Fernández
description: My personal web page
favicon: /assets/img/cara.jpg
baseurl: https://mfernam.github.io
url: https://mfernam.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Miguel Fernández
  title: Consultor y desarrollador
  address: Alicante, Spain
  email: losmeus@gmail.com
  link: http://mfernam.github.io
  weibo:
  github: mfernam
  linkedin: mfernam
  twitter: mfernam
#  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  #  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Universidad de Alicante
      location: Alicante, Spain
      title: Técnico
      started: 2010
      duration: (2010 - 2017)
      description: Proyecto Ramon Llull. Refactorización del código usando el patrón MVP, implementación de inyección de dependencias con el framework Spring. Control de usuarios de la aplicación mediante certificados electrónicos, actualización automática de la aplicación de escritorio. Instalación y mantenimiento de la web del proyecto con el CMS WordPress. Tareas de formación y soporte técnico a usuarios.
    
  educationHistory:
    - education1:
      organization: Universidad de Alicante
      location: Alicante, Spain
      degree: Licenciado
      major: Geografía
      #started: 2005
      duration: (19955 - 2002)
      #description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
      
    - education2:
      organization: Instituto Cibernos
      location: Alicante, Spain
      degree: Máster
      major: Sistemas de Información Geográfica
      #started: 2005
      duration: (2003)
      #description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  
    - education3:
      organization: Universitat Oberta de Catalunya
      location: Barcelona, Spain
      degree: Máster
      major: Software Libre
      #started: 2005
      duration: (2010 - 2013)
      #description: 
  languages:
    - language1:
      name: Spanish
      proficiency: Native
    - language2:
      name: Valencian
      proficiency: Professional
    - language3:
      name: English
      proficiency: Intermediate
    - language4:
      name: French
      proficiency: Limit
    - language5:
      name: Portuguese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C#
      percentage: 100%
    - skill2:
      name: PHP
      percentage: 100%
    - skill3:
      name: Java
      percentage: 70%
    - skill4:
      name: SQL
      percentage: 90%
